### ISSUE TITLE
CSS 学习

### ISSUE THREAD

**Issue by shaopower** [shaopower/juno#3]
作为从 .net 开始的码农，个人感觉 CSS 比 JS 难的多得多得多  
* 样式文件里那密密麻麻数不清的关键词保留字枚举值  
* 时常看到同事在那抓狂的招呼着各浏览器大爷  
我决定轻易不进这雷区  

然而俗话说得好
> 常在河边走，哪有不湿鞋  

不是所有公司都有专职重构的同学，也只好硬着头皮一路爬过来了  

回过头看也不是那么的天雷滚滚，可能是下面这些关系
> 没吃过猪肉还没见过猪跑么
* 样式文件看了这么多年，不说知根知底也大都脸熟了
* 各浏览器样式规范的逐渐统一 & 老版本浏览器退出市场
* 样式调试友好度增加，即改即得
* 最近的 RN 开发，flex 布局 和 CSS in JS 模式 的无门槛乱入 

并不是说 CSS 变简单了，手机端的普及 & 硬件性能的提升，CSS 的功能只会更强大能完成的效果更炫酷  

只是趁着这个自我膨胀的时机学习下
* < CSS3: 知识补完
* \>= CSS3: 学习探索
* 手机端
* LESS & SASS

**Comment by shaopower** [comment]
# CSS 的历史
这东西貌似是被逼出来的规范 
> HTML 混杂了 font big 非描述结构标签，一片混论

# demo
```html
<div id="content" class="wrapper">
    <p class="warn"></p>
    <ul>
        <li></li>
        <li></li>
        <li></li>
    </ul>
    <img class="banner" src="">
    <a href="/">click</a>
</div>
```

# 选择器
最早在 jQuery 里接触的这个。。

* tag
```css
/* 0,0,0,1 */
div { width: 100px } 
```

* #id
```css
/* 0,1,0,0 */
#content { width: 200px } 
```

* .class
```css
/* 0,0,1,0 */
.wrapper { width: 150px } 
```

* 属性选择器
[attr='']
```css
/* 0,0,1,0 */
[href='/'] { color: blue }
```

* 伪类
```css
/* 0,0,1,0 */
:hover { color: #666 } 
```

* 伪元素
为了区分伪类 推荐 ::
```css
/* 0,0,0,1  css2.1 */
/* 0,0,0,0  css2.0 */
::after { content: ' just do it' } 
```

* 组合
    * /^tag{0,1}[#id|.class]\*[属性选择器]\*[伪类|伪元素]$/
    假定此为泛型 \<css>
    ```css
    /* 0,1,0,1 */
    div#content { width: 250 } 
    /* 0,1,1,0 */
    .wrapper#content { width: 300 }
    /* 0,0,2,0 */
    .banner[src=""] { width: 100; height: 100 }
    /* 0,0,1,2 */
    p.warn::after { content: ' catch' }
    ```

    * /^\<css>( \<css>)*$/
    后代
    伪元素只能放在末尾
    ```css
    /* 0,1,1,3 */
    div#content p.warn li { font-size: 14px }
    ```

    * /^\<css>( > \<css>)*$/
    父子
    伪元素只能放在末尾

    * /^\<css>( + \<css>)*$/
    相邻
    伪元素智能放在末尾

    * mix(后代, 父子, 相邻)
    选择器 后代，父子，相邻 可组合，但伪元素只能出现一次且放在末尾
    假定 mixed => \<mixed>

    * /^\<mixed>[, \<mixed>]*$/
    分组
    伪元素在每个分组中只能出现一次且放在所在分组的末尾
    ```css
    /* #content: 0,1,0,0 */
    /* .warn: 0,0,1,0 */
    /* a:hover: 0,0,1,0 */
    /* a:after: 0,0,0,2 css2.1 */
    /* a:after: 0,0,0,1 css2.0 */
    #content, .warn, a:hover, a:after { color: red } 
    ```

# 特殊性
0,0,0,0
[inline],[#id],[.class|[src=""]|:hover],[tag|::before(css2.1)]
\* => 0
0 > null
a,b,c,d !== a * 1000 + b * 100 + c * 10 + d * 1

!important

# 权重
# 继承
# 层叠
# 盒模型
